Repository 2023-Summer-Bootcamp-Team-G/frontend, pull requests merged in 2023-07, with the labels that each got.

#4 [Feat/#1] 입력값에 따른 동적 키워드 태그 구현
  src/components/KeywordTag/KeywordTag.tsx
Labels: 기능구현

#13 [Feat/#5] 공용 컴포넌트 - 질문 카드 구현
  src/components/QuestionCard/QuestionCard.tsx
Labels: 기능구현

#16 [Refactor/#15] 키워드 태그, 질문카드 리팩토링
  src/components/KeywordTag/KeywordTag.tsx
  src/components/QuestionCard/QuestionCard.tsx
Labels: 리팩토링

#18 [Feat/#17] 공용 컴포넌트 - 캐릭터 박스 구현
  src/components/CharBox/CharBox.tsx
  src/components/KeywordTag/KeywordTag.tsx
  src/components/QuestionCard/QuestionCard.tsx
Labels: 기능구현

#19 [Feat/#11] 공용 컴포넌트 - 인풋 구현
  index.html
  src/App.tsx
  src/components/Btn/Btn.tsx
  src/components/Btn/RoundBtn.tsx
  src/components/Input/AnswerInput.tsx
  src/components/Input/LoginInput.tsx
  src/components/Input/QuestionInput.tsx
  src/styles/GlobalStyle.ts
Labels: 기능구현

#22 chore : react-router 세팅
  package.json
  src/App.tsx
  src/main.tsx
  yarn.lock
Labels: 환경설정

#25 [Feat/#23] 페이지 - 질문 답변 페이지 구현
  src/components/BackGround/BackGround.tsx
  src/components/Btn/RoundBtn.tsx
  src/components/Input/AnswerInput.tsx
  src/pages/AnswerPage.tsx
  src/styles/backgroundStyle.ts
Labels: 기능구현

#26 [Feat/#24] 공용컴포넌트 - pie차트
  package.json
  src/components/Chart/Chart.tsx
  yarn.lock
Labels: 기능구현

#30 [Feat/#28] 질문 생성 페이지 구현
  src/components/QuestionCard/QuestionCard.tsx
  src/pages/QuestionPage.tsx
Labels: 퍼블리싱

#31 [Feat/#27] 로딩스피너 컴포넌트 구현
  .gitignore
  package.json
  src/components/Loading/Loading.tsx
  src/components/Loading/Spinner.tsx
Labels: 기능구현

#34 [Feat/#29] 로그인 및 회원가입 페이지 구현
  package.json
  src/App.tsx
  src/components/BackGround/BoxContainer.tsx
  src/components/Input/LoginInput.tsx
  src/constants/variants.ts
  src/pages/AnswerPage.tsx
  src/pages/LoginPage.tsx
  src/pages/Main.tsx
  src/pages/SignUpPage.tsx
  src/styles/GlobalStyle.ts
  src/styles/backgroundStyle.ts
  src/styles/theme.ts
Labels: 기능구현

#38 [Feat/#32] 캐릭터 상세페이지 구현 및 다른 파일 코드 수정
  src/App.tsx
  src/pages/AnswerPage.tsx
  src/pages/CharResultPage.tsx
  src/pages/QuestionPage.tsx
Labels: 기능구현

#41 [Feat/#40] 마이페이지 구현
  src/App.tsx
  src/components/Chart/Chart.tsx
  src/components/Input/NickNameInput.tsx
  src/components/Tab/Tab.tsx
  src/pages/MyPage.tsx
  src/pages/YourPage.tsx
  src/utils/data.ts
Labels: 기능구현

#47 [Feat/#44]회원가입 페이지 구현
  package.json
  src/apis/config.ts
  src/components/Btn/RoundBtn.tsx
  src/components/Input/LoginInput.tsx
  src/pages/SignUpPage.tsx
Labels: 기능구현

#49 [Feat/#46] 로그인 페이지 api 연동
  src/components/Btn/RoundBtn.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
Labels: 기능구현

#51 [Feat/#43] 질문생성페이지 서버연결구현
  src/components/Input/QuestionInput.tsx
  src/pages/QuestionPage.tsx
Labels: 기능구현

#52 [Feat/#50] MyPage, YourPage api 연결, 컴포넌트 api 연결 및 수정
  src/components/CharBox/CharBox.tsx
  src/components/FlipCard/FlipCard.tsx
  src/components/Tab/Tab.tsx
  src/pages/MyPage.tsx
  src/pages/YourPage.tsx
Labels: 기능구현

#53 [Feat/#48] 답변 페이지 구현
  src/components/Btn/RoundBtn.tsx
  src/components/Input/AnswerInput.tsx
  src/pages/AnswerPage.tsx
  src/pages/QuestionPage.tsx
Labels: 기능구현

#55 [Refactor]질문 post api수정
  src/components/Input/AnswerInput.tsx
  src/pages/AnswerPage.tsx
  src/pages/QuestionPage.tsx
Labels: 리팩토링

#57 [Chore/#56] zustand설치
  package.json
Labels: 환경설정

#59 [Feat/#58]: pollId 상태관리
  src/pages/AnswerPage.tsx
  src/pages/QuestionPage.tsx
  src/stores/pollId.ts
Labels: 기능구현

#63 [Feat/#60] userId 상태관리 적용
  src/components/Tab/Tab.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/QuestionPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/YourPage.tsx
  src/stores/userStore.ts
Labels: 기능구현

#65 [Feat/#62] : answerpage 모달,로딩스피너 구현
  src/components/Input/NickNameInput.tsx
  src/pages/AnswerPage.tsx
  src/stores/taskId.ts
Labels: 기능구현

#66 [Feat/#64] nickName 상태관리 적용
  src/components/Tab/Tab.tsx
  src/pages/AnswerPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/QuestionPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/YourPage.tsx
  src/stores/pollId.ts
  src/stores/taskId.ts
  src/stores/userStore.ts
Labels: 기능구현

#70 [Design/#68] login, signup 퍼블리싱 수정 및 애니메이션 추가
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  src/stores/userStore.ts
Labels: 퍼블리싱

#71 [Feat/#61]result page 구현
  src/App.tsx
  src/components/Btn/RoundBtn.tsx
  src/components/FlipCard/FlipCard.tsx
  src/components/FlipCard/FlipModal.tsx
  src/pages/AnswerPage.tsx
  src/pages/ResultPage.tsx
  src/stores/keywords.ts
  src/stores/urls.ts
Labels: 기능구현

#73 [Design/#67] mainpage 퍼블리싱 수정 + 다른 페이지들 창 사이즈 줄이면 컴포넌트 넘어가는 사항 수정
  src/pages/AnswerPage.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
  src/pages/QuestionPage.tsx
  src/pages/ResultPage.tsx
  src/pages/YourPage.tsx
Labels: 기능구현, 퍼블리싱

#75 [Feat/#72] 디테일 페이지 api 연결
  src/components/CharBox/CharBox.tsx
  src/components/FlipCard/FlipCard.tsx
  src/components/QnA/QnA.tsx
  src/components/Tab/Tab.tsx
  src/pages/DetailPage.tsx
  src/pages/ResultPage.tsx
  src/stores/id.ts
Labels: 기능구현

#76 [Feat/#74] 동적 메타태그 페이지마다 적용
  index.html
  src/pages/AnswerPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
Labels: 기능구현

#79 [Feat/#78] 디테일 페이지 api 수정
  src/components/Btn/RoundBtn.tsx
  src/components/FlipCard/FlipCard.tsx
  src/components/Input/LoginInput.tsx
  src/pages/AnswerPage.tsx
  src/pages/DetailPage.tsx
  src/pages/MyPage.tsx
  src/pages/ResultPage.tsx
Labels: 기능구현

#81 [Feat/#80]answer page 링크 수정
  src/App.tsx
  src/pages/AnswerPage.tsx
  src/pages/QuestionPage.tsx
  src/stores/pollId.ts
Labels: 기능구현

#84 [Feat/#77] 중복 캐릭터 api 구현
  src/components/FlipCard/FlipCard.tsx
  src/pages/MyPage.tsx
  src/pages/ResultPage.tsx
  src/pages/YourPage.tsx
Labels: 기능구현

#85 [feat/#82]링크복사
  src/App.tsx
  src/components/FlipCard/FlipModal.tsx
  src/components/Tab/Tab.tsx
  src/pages/AnswerPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/QuestionPage.tsx
  src/stores/link.ts
  src/stores/poll.ts
  src/stores/userStore.ts
Labels: 기능구현

#86 Revert "[feat/#82]링크복사"
  src/App.tsx
  src/components/FlipCard/FlipModal.tsx
  src/components/Tab/Tab.tsx
  src/pages/AnswerPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/QuestionPage.tsx
  src/stores/link.ts
  src/stores/poll.ts
  src/stores/userStore.ts
Labels: 기능구현

#93 [Refactor/#92}경로수정
  src/App.tsx
  src/components/FlipCard/FlipModal.tsx
  src/components/Swipe/Swipe.tsx
  src/components/Tab/Tab.tsx
  src/pages/AnswerPage.tsx
  src/pages/DetailPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/QuestionPage.tsx
Labels: 리팩토링

#97 [Feat/#95] 비밀번호 확인 인풋 + 로그인, 회원가입 양식
  src/components/Btn/SignBtn.tsx
  src/components/Input/LoginInput.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
Labels: 기능구현, 퍼블리싱

#99 feat:질문지 링크 복사 퍼블리싱 수정,색버튼, 그림체 버튼 수정
  index.html
  src/components/Btn/Btn.tsx
  src/components/choice/choice.tsx
  src/components/choice/color.tsx
  src/hooks/.gitkeep
  src/hooks/useCheckAuth.ts
  src/pages/AnswerPage.tsx
  src/pages/DetailPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/QuestionPage.tsx
  src/pages/ResultPage.tsx
  src/pages/SignUpPage.tsx
  src/stores/testStore.ts
  src/utils/data.ts
Labels: 기능구현

#101 [Fix/#100] signbtn disabled 수정
  src/components/Btn/SignBtn.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
Labels: 오류수정

#107 [Fix/#103] detailpage 답변자 닉네임 오류 해결
  src/pages/AnswerPage.tsx
  src/pages/DetailPage.tsx
  src/pages/MyPage.tsx
Labels: 오류수정
