Repository 2023-Summer-Bootcamp-Team-G/frontend, pull requests merged in 2023-08, with the labels that each got.

#113 [Feat/#110] answerpage 답변 다 안했을 시 alert + navigate 안되게
  package.json
  src/pages/AnswerPage.tsx
Labels: 기능구현, 환경설정

#118 [Feat]모달수정
  src/pages/AnswerPage.tsx
Labels: 기능구현

#120 [Refactor/#119] 로그인, 회원가입 유효성 검사 코드 수정
  src/components/Btn/SignBtn.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
Labels: 리팩토링

#122 [Feat/#121] 메타태그 경로에 맞는 이미지 url 설정 + 배포 url 설정
  index.html
  src/pages/AnswerPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
Labels: 기능구현

#125 [Feat/#123] 마이페이지 홈버튼
  src/App.tsx
  src/components/Input/AnswerInput.tsx
  src/components/Tab/Tab.tsx
  src/pages/AnswerPage.tsx
  src/pages/DetailPage.tsx
  src/pages/MyPage.tsx
  src/pages/QuestionPage.tsx
  src/pages/ResultPage.tsx
  src/pages/YourPage.tsx
Labels: 기능구현

#126 [Refactor/#117] 중복 캐릭터, 차트 색 수정
  package.json
  src/assets/animation_lkt9dpm7.json
  src/components/Chart/Chart.tsx
  src/components/FlipCard/FlipCard.tsx
  src/components/Swipe/Swipe.tsx
  src/components/Tab/Tab.tsx
  src/pages/MyPage.tsx
  src/styles/GlobalStyle.ts
Labels: 리팩토링

#128 [Design]:박스 깨지는거 수정
  src/components/BoxContainer/BoxContainer.tsx
  src/pages/AnswerPage.tsx
  src/pages/DetailPage.tsx
  src/pages/MyPage.tsx
  src/pages/QuestionPage.tsx
  src/pages/ResultPage.tsx
  src/pages/SignUpPage.tsx
  src/styles/Container.ts
  src/styles/GlobalStyle.ts
Labels: 퍼블리싱

#129 [Feat/#127] 닉네임인풋 모달창 엔터 가능
  src/App.tsx
  src/components/FlipCard/FlipModal.tsx
  src/components/Input/NickNameInput.tsx
  src/components/Loading/BoxInDog.tsx
  src/components/Loading/Loading.tsx
  src/components/Loading/Spinner.tsx
  src/pages/AnswerPage.tsx
  src/pages/DetailPage.tsx
  src/pages/ErrorPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/SignUpPage.tsx
Labels: 기능구현

#135 [Design/#98] mui tab, high chart 색상 변경
  src/components/Chart/Chart.tsx
  src/components/Swipe/styles.css
  src/components/Tab/Tab.tsx
  src/pages/AnswerPage.tsx
  src/pages/MyPage.tsx
Labels: 퍼블리싱

#136 [Feat/#133] 인풋을 textarea로 수정
  package.json
  src/components/FlipCard/FlipCard.tsx
  src/components/Input/AnswerInput.tsx
Labels: 기능구현

#140 [Feat/#139] 캐릭터 생성 시 500에러 뜰 때 경고창
  src/components/Loading/Loading.tsx
  src/pages/AnswerPage.tsx
  src/pages/ResultPage.tsx
  src/utils/utils.ts
Labels: 기능구현

#141 [Design]mypage 크기 수정
  src/components/CharBox/CharBox.tsx
  src/components/FlipCard/FlipCard.tsx
  src/components/Tab/Tab.tsx
  src/pages/MyPage.tsx
Labels: 퍼블리싱

#145 [Design/#143] 플립카드 및 키워드 크기 줄이기
  src/components/FlipCard/FlipCard.tsx
  src/components/KeywordTag/KeywordTag.tsx
Labels: 퍼블리싱

#146 [Feat]다운로드 기능 구현
  src/pages/DetailPage.tsx
  src/pages/MyPage.tsx
Labels: 기능구현
